### ISSUE TITLE
Manage multiple accounts

### ISSUE THREAD

**Issue by SaschaWeisenberger** [powerpaul17/nc_money#60] opened 2024-01-02 08:18 UTC
**Is your feature request related to a problem? Please describe.**
Me and my wife have multiple accounts (saving for holiday, renovation etc...) and some accounts which represent loans. 

**Describe the solution you'd like**
I would be nice to have multiple, independent accounts in the app, including the feature to transfer money from one account to another. A loan account could also have an automation where you provide the information about the conditions (3%, 500€ every month over 10 years) and there will be automatic transfers to this loan from a specific account.

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by powerpaul17** [comment] 2024-01-02 20:20
Hello, there is already the possibility to add as many accounts as you want. In case you are thinking about sharing accounts between you and your wife, this is a duplicate of #42  (or #39). Loans are already tracked by #32

**Closed by powerpaul17** 2024-01-02 20:20 UTC
