### ISSUE TITLE
no settings menu?

### ISSUE THREAD

**Issue by punkyard** [powerpaul17/nc_money#22] opened 2022-11-04 17:04 UTC
hi
is there a way to share an account with other users?
or is it an app for lonely people?
impossible to remove an entry?

plus, there are some display twitchings on chrome/brave: scroll bars appear and disappear, so do white squares when moving the mouse over the text fields ..?

![Capture d’écran 2022-11-04 à 17 56 17](https://user-images.githubusercontent.com/59349105/200033874-e67103ed-7ff7-4778-a556-283057c344a1.png)

![Capture d’écran 2022-11-04 à 17 57 08](https://user-images.githubusercontent.com/59349105/200033976-2a19710e-a6c3-4a81-8155-51e50f989c50.png)

thanks, i'm currently trying out your app :)

**Comment by powerpaul17** [comment] 2022-11-04 20:05
This app is still in very early stages (0.x version), so there are a lot of desirable features still missing. You have to be patient please. So currently it is for "lonely people".. :smile: 

Regarding the other issue, I tested on Chromium and there is the white box in the bottom right but it seems to be related to the scroll bars (which Chrome draws). I don't know if there is a fix but I'll look into it. The other white boxes you mention I cannot reproduce on my computer. Do you have more information about that?

**Comment by punkyard** [comment] 2022-11-04 20:17
i'll be patient, and pleased to help you when can ✌️
i've then added the French missing terms .. that's not much, but i'll try to come back here and hit you with useful ideas and desires, and turn your work into a pleasurable multi-handed app ^^

**Comment by powerpaul17** [comment] 2022-12-21 11:50
I'll close this for now. As for the scroll bars and white squares I assume it also has to do with your custom theme..

**Closed by powerpaul17** 2022-12-21 11:50 UTC

**Comment by punkyard** [comment] 2022-12-21 12:56
hi
no this was with NC24, i wasnt using the nc dark theme at that time.

**Comment by powerpaul17** [comment] 2023-01-31 18:54
So, is it fixed now in NC 25?

**Comment by punkyard** [comment] 2023-02-01 05:22
> So, is it fixed now in NC 25?

hi Paul, but sorry i wont be able to tell, we've stopped using this app.

**Comment by powerpaul17** [comment] 2023-02-01 08:50
Ok, no problem, just wanted to check the open issues.. :slightly_smiling_face:
